### ISSUE TITLE
MemoryError: Unable to allocate 12.9 GiB for an array with shape (207400, 9, 9, 103) and data type float64

### ISSUE THREAD

**Issue by Zhandiwa** [majidseydgar/Res-CP#1]
When I want to reproduce the embedding features, I encountered the following problem: MemoryError: Unable to allocate 12.9 GiB for an array with shape (207400, 9, 9, 103) and data type float64.
What should I do about it?

**Comment by majidseydgar** [comment]
Hi, 
The error should be belong to the "RCN" for reproducing the embedded features. Since this process requires loading all the samples in the memory, you got the memory error. 

I've uploaded the embedded features (obtained from 10 labeled samples per class) for all the datasets in this link: https://drive.google.com/file/d/1Wr3TYn7-Vsv3MtIa70R6B_-hWOR04Xsh/view

However, if you need embedded features with different setting, I may be able to reproduce the results and share them with you.

**Comment by Zhandiwa** [comment]
Thank you for your reply！
I made a little modification to the loss function in your code, so I needed to regenerate this file, and this error occurred. Are there any other solutions? For example, by modifying the data type.

**Comment by majidseydgar** [comment]
I think a simple way to decrease the memory load is to break the hole HSI into a several pieces before the patch extraction. The extracted patches need to be saved into your hard disk and then load by Pytorch data loader. Specifically, "1-RCN/datasets.py" (line 182) is responsible for high memory load. To modify it, break "self.data" to several matrix and "self.Total_size, self.total_indices"  to several arrays, and then put the RCN/datasets.py" (line 182:195) in a loop to iteratively construct "all_iter" variable. 

I will update the repository in the next days and add a solution for this problem. Please stay tuned.

**Comment by Zhandiwa** [comment]
Thank you very much for your reply.  And gave me a lot of help! Wish you a happy life!

**Comment by Zhandiwa** [comment]
Could you please provide the PRCLSTM and PRCLSTM II codes?
